[workspace]
members = ["ultraapi", "ultraapi-macros", "examples/ultraapi-example", "examples/grpc-example", "examples/ultraapi-cli", "examples/graphql-example", "examples/sqlx-example"]
resolver = "2"
